#!/usr/bin/env python3
"""Compare Python track coordinates against Mathematica reference tracks.

Usage:
    python scripts/validate_tracks.py

Requires:
    1. Mathematica reference tracks in models/reference/ (JSON files)
       (generated by: wolframscript -file scripts/export_reference_tracks.wls)
    2. Model weights at ~/.kymobutler/models/
"""

import json
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).parent.parent
REF_DIR = REPO_ROOT / "models" / "reference"
TEST_DIR = REPO_ROOT / "tests" / "data"
OUT_DIR = REPO_ROOT / "tests" / "data" / "comparison"


def load_mma_tracks(json_path: Path) -> list[list[tuple[int, int]]]:
    """Load Mathematica reference tracks from JSON."""
    with open(json_path) as f:
        data = json.load(f)

    # Handle both unidirectional (ant/ret keys) and bidirectional (tracks key) formats
    if "tracks" in data:
        tracks_raw = data["tracks"]
    elif "ant" in data:
        tracks_raw = data["ant"]
    else:
        return []

    tracks = []
    for trk in tracks_raw:
        # Each track is a list of {time, space} dicts
        points = [(p["time"], p["space"]) for p in trk]
        tracks.append(points)
    return tracks


def hausdorff_distance(track_a: list[tuple[int, int]], track_b: list[tuple[int, int]]) -> float:
    """Compute the Hausdorff distance between two tracks."""
    a = np.array(track_a, dtype=np.float64)
    b = np.array(track_b, dtype=np.float64)

    # For each point in A, find min distance to B
    dist_a_to_b = np.array([np.min(np.sqrt(np.sum((b - p) ** 2, axis=1))) for p in a])
    dist_b_to_a = np.array([np.min(np.sqrt(np.sum((a - p) ** 2, axis=1))) for p in b])

    return float(max(np.max(dist_a_to_b), np.max(dist_b_to_a)))


def match_tracks(
    python_tracks: list[list[tuple[int, int]]],
    mma_tracks: list[list[tuple[int, int]]],
) -> list[tuple[int, int, float]]:
    """Match Python tracks to Mathematica tracks by minimum mean distance.

    Returns list of (python_idx, mma_idx, mean_distance) tuples.
    """
    if not python_tracks or not mma_tracks:
        return []

    matches = []
    used_mma = set()

    for pi, py_trk in enumerate(python_tracks):
        py_arr = np.array(py_trk, dtype=np.float64)
        best_mi = -1
        best_dist = float("inf")

        for mi, mma_trk in enumerate(mma_tracks):
            if mi in used_mma:
                continue
            mma_arr = np.array(mma_trk, dtype=np.float64)
            # Mean of min distances from python to mma
            dists = [np.min(np.sqrt(np.sum((mma_arr - p) ** 2, axis=1))) for p in py_arr]
            mean_dist = np.mean(dists)
            if mean_dist < best_dist:
                best_dist = mean_dist
                best_mi = mi

        if best_mi >= 0 and best_dist < 20:  # threshold for matching
            matches.append((pi, best_mi, best_dist))
            used_mma.add(best_mi)

    return matches


def compare_tracks(
    name: str,
    python_tracks: list[list[tuple[int, int]]],
    mma_tracks: list[list[tuple[int, int]]],
) -> dict:
    """Compare Python and Mathematica tracks and print report."""
    print(f"\n{'=' * 60}")
    print(f"  {name}")
    print(f"{'=' * 60}")
    print(f"  Python tracks: {len(python_tracks)}")
    print(f"  Mathematica tracks: {len(mma_tracks)}")

    # Note: Mathematica uses 1-indexed coordinates, Python uses 0-indexed
    # Adjust Mathematica coordinates to 0-indexed for comparison
    mma_tracks_0idx = [[(t - 1, s - 1) for t, s in trk] for trk in mma_tracks]

    matches = match_tracks(python_tracks, mma_tracks_0idx)
    print(f"  Matched tracks: {len(matches)}")

    if matches:
        dists = [d for _, _, d in matches]
        print(f"  Mean match distance: {np.mean(dists):.2f} pixels")
        print(f"  Max match distance:  {np.max(dists):.2f} pixels")

        # Per-match details
        for pi, mi, dist in sorted(matches, key=lambda x: x[2], reverse=True)[:5]:
            py_len = len(python_tracks[pi])
            mma_len = len(mma_tracks_0idx[mi])
            print(f"    py[{pi}]({py_len}pts) <-> mma[{mi}]({mma_len}pts): dist={dist:.2f}")

    unmatched_py = set(range(len(python_tracks))) - {m[0] for m in matches}
    unmatched_mma = set(range(len(mma_tracks_0idx))) - {m[1] for m in matches}
    if unmatched_py:
        print(f"  Unmatched Python tracks: {len(unmatched_py)}")
    if unmatched_mma:
        print(f"  Unmatched Mathematica tracks: {len(unmatched_mma)}")

    return {
        "name": name,
        "python_count": len(python_tracks),
        "mma_count": len(mma_tracks),
        "matched": len(matches),
        "mean_dist": float(np.mean([d for _, _, d in matches])) if matches else float("inf"),
    }


def save_overlay_comparison(
    name: str,
    image: np.ndarray,
    python_tracks: list[list[tuple[int, int]]],
    mma_tracks: list[list[tuple[int, int]]],
    out_dir: Path,
) -> None:
    """Save side-by-side overlay comparison: Python tracks | Mathematica tracks."""
    from PIL import Image as PILImage

    from kymobutler.io_utils import _draw_line

    h, w = image.shape[:2]
    if image.max() <= 1.0:
        gray = (image * 255).astype(np.uint8)
    else:
        gray = image.astype(np.uint8)

    # Python overlay
    py_rgb = np.stack([gray, gray, gray], axis=-1).copy()
    rng = np.random.default_rng(42)
    for trk in python_tracks:
        color = rng.integers(50, 255, size=3).tolist()
        for i in range(len(trk) - 1):
            r0, c0 = trk[i]
            r1, c1 = trk[i + 1]
            _draw_line(py_rgb, int(r0), int(c0), int(r1), int(c1), color)

    # Mathematica overlay (convert from 1-indexed to 0-indexed)
    mma_rgb = np.stack([gray, gray, gray], axis=-1).copy()
    rng2 = np.random.default_rng(42)
    for trk in mma_tracks:
        color = rng2.integers(50, 255, size=3).tolist()
        points_0idx = [(t - 1, s - 1) for t, s in trk]
        for i in range(len(points_0idx) - 1):
            r0, c0 = points_0idx[i]
            r1, c1 = points_0idx[i + 1]
            if 0 <= r0 < h and 0 <= c0 < w and 0 <= r1 < h and 0 <= c1 < w:
                _draw_line(mma_rgb, int(r0), int(c0), int(r1), int(c1), color)

    # Side by side
    separator = np.full((h, 2, 3), 128, dtype=np.uint8)
    combined = np.concatenate([py_rgb, separator, mma_rgb], axis=1)

    out_dir.mkdir(parents=True, exist_ok=True)
    PILImage.fromarray(combined).save(out_dir / f"{name}_track_comparison.png")
    print(f"  Saved: {out_dir / f'{name}_track_comparison.png'}")


def main():
    if not REF_DIR.exists():
        print(f"Reference directory not found: {REF_DIR}")
        print("Run: wolframscript -file scripts/export_reference_tracks.wls")
        return

    from kymobutler.models.weights import load_default_models
    from kymobutler.preprocessing import load_and_preprocess
    from kymobutler.segmentation import segment_bidirectional, segment_unidirectional
    from kymobutler.tracking import track_bidirectional, track_unidirectional

    print("Loading ONNX models...")
    models = load_default_models()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    results = []

    # Unidirectional tests
    for test_name in ("unitest", "unitest2"):
        ref_path = REF_DIR / f"{test_name}_tracks.json"
        if not ref_path.exists():
            print(f"Skipping {test_name}: no reference tracks")
            continue

        with open(ref_path) as f:
            ref_data = json.load(f)

        image_path = TEST_DIR / f"{test_name}.png"
        _, raw, preprocessed, pred_dict = segment_unidirectional(image_path, models["uninet"])
        ant_tracks, ret_tracks = track_unidirectional(
            pred_dict, preprocessed.shape, threshold=0.2, min_size=3, min_frames=3
        )

        # Compare anterograde tracks
        mma_ant = [[tuple(p.values()) for p in trk] for trk in ref_data.get("ant", [])]
        py_ant = [t.points for t in ant_tracks]
        stats = compare_tracks(f"{test_name}_ant", py_ant, mma_ant)
        results.append(stats)
        save_overlay_comparison(f"{test_name}_ant", raw, py_ant, mma_ant, OUT_DIR)

        # Compare retrograde tracks
        mma_ret = [[tuple(p.values()) for p in trk] for trk in ref_data.get("ret", [])]
        py_ret = [t.points for t in ret_tracks]
        if mma_ret or py_ret:
            stats = compare_tracks(f"{test_name}_ret", py_ret, mma_ret)
            results.append(stats)

    # Bidirectional test
    ref_path = REF_DIR / "bitest_tracks.json"
    if ref_path.exists():
        with open(ref_path) as f:
            ref_data = json.load(f)

        image_path = TEST_DIR / "bitest.png"
        was_negated, raw, preprocessed, pred = segment_bidirectional(image_path, models["binet"])
        tracks = track_bidirectional(
            pred, preprocessed, was_negated, threshold=0.2,
            vision_net=models.get("decnet"), min_size=10, min_frames=10,
        )

        mma_tracks = [[tuple(p.values()) for p in trk] for trk in ref_data.get("tracks", [])]
        py_tracks = [t.points for t in tracks]
        stats = compare_tracks("bitest", py_tracks, mma_tracks)
        results.append(stats)
        save_overlay_comparison("bitest", raw, py_tracks, mma_tracks, OUT_DIR)

    # Summary
    print(f"\n{'=' * 60}")
    print("  SUMMARY")
    print(f"{'=' * 60}")
    for r in results:
        status = "OK" if r["mean_dist"] < 3 else "DIFFERS"
        print(
            f"  [{status}] {r['name']}: "
            f"py={r['python_count']}, mma={r['mma_count']}, "
            f"matched={r['matched']}, mean_dist={r['mean_dist']:.2f}"
        )


if __name__ == "__main__":
    main()
